version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    platform: linux/amd64
    command : --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
       - db:/var/lib/mysql


  springboot:
    container_name: springboot
    restart: always
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mysql
    env_file: ./.env
    environment:
      WAIT_HOSTS: mysql:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/${DB_DATABASE}
      # SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      # SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
    
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db:  